apiVersion: v1
kind: Pod
metadata:
  name: pod-myapp
  namespace: antoine-test
  labels:
    app: MyApp
    tier: frontend
spec:
  containers:
    - name: myapp-container
      image: nginxdemos/hello:latest
