apiVersion: v1
kind: Service
metadata:
  name: service-myapp
  namespace: antoine-test
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: MyApp
    tier: frontend
  
