apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-myapp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monchart.labels" . | nindent 4 }}
data:
  APPID: "{{ required ".Values.appId entry is required!" .Values.appId }}"
