apiVersion: v1
kind: Secret
metadata:
  name: secret-myapp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monchart.labels" . | nindent 4 }}
type: Opaque
stringData:
  PASSWD: "{{ required ".Values.password entry is required!" .Values.password }}"
