kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: longhornpvc
  namespace: <prenom>-test3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 40Mi
