kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: longhornpvc
  namespace: <prenom>-test3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 20Mi
