apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticpv-antoine
  namespace: <prenom>-test3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/staticpv-antoine
