kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: staticpvc
  namespace: <prenom>-test3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 256Mi
