apiVersion: v1
kind: Service
metadata:
  name: svc-monapp-helloworld
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: monapp-helloworld
    tier: frontend
  clusterIP: None
