apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-elasticsearch
  namespace: estest-<prenom>
  labels:
    app: kube-logging
    tier: elasticsearch
data:
  discovery.seed_hosts: "statefulset-es-cluster-0.service-elasticsearch,statefulset-es-cluster-1.service-elasticsearch,statefulset-es-cluster-2.service-elasticsearch"
  cluster.initial_master_nodes: "statefulset-es-cluster-0,statefulset-es-cluster-1,statefulset-es-cluster-2"
  cluster.name: "formationk8s"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
